format = """\
[░▒▓](#a3aed2)\
[ 󰣇 ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\
\n$character"""

right_format = """\
[$time](fg:#090c0c bg:#a3aed2)\
[](fg:#769ff0)\
$memory_usage
[▓▒░](#769ff0)\
"""

continuation_prompt = "↳ "

add_newline = false # Disable the blank line at the start of the prompt
scan_timeout = 20
command_timeout = 20

[character]
success_symbol = "[█ ](bold green)"
error_symbol = "[█ ](bold red)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)([ $read_only ]($read_only_style))"
read_only = " "
read_only_style = "fg:#e02020 bg:#769ff0"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "🗎 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = " "
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = "bg:#769ff0"
format = '[[ 󰍛 $ram | $swap ](fg:#e3e5e5 bg:#769ff0)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#a3aed2"
format = '[  $time ]($style)'
